# Generated by Django 5.1.4 on 2025-01-04 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='date_inscription',
        ),
    ]
