# Generated by Django 5.1.4 on 2025-01-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_remove_subscriptionmodel_category_and_more'),
        ('user', '0002_remove_usermodel_actif_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonModel',
            new_name='ProspectModel',
        ),
    ]
