# Generated by Django 5.1.4 on 2025-01-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_devis', models.CharField(max_length=20, unique=True)),
                ('prix_calculé', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_validite', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
