# Generated by Django 5.1.4 on 2025-01-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulationmodel',
            name='date_validite',
        ),
        migrations.RemoveField(
            model_name='simulationmodel',
            name='person',
        ),
        migrations.RemoveField(
            model_name='simulationmodel',
            name='prix_calculé',
        ),
        migrations.RemoveField(
            model_name='simulationmodel',
            name='reference_devis',
        ),
        migrations.AddField(
            model_name='simulationmodel',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulationmodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='simulationmodel',
            name='puissance_fiscale',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulationmodel',
            name='quoteReference',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='simulationmodel',
            name='type_produitAssurance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='simulationmodel',
            name='valeur_venale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
