# Generated by Django 5.1.4 on 2025-01-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_remove_simulationmodel_date_validite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationmodel',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
