# Generated by Django 5.1.4 on 2025-01-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0004_alter_simulationmodel_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationmodel',
            name='annee_vehicule',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
