# Generated by Django 5.1.4 on 2025-01-04 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('couleur', models.CharField(max_length=30)),
                ('puissance_fiscale', models.PositiveIntegerField()),
                ('date_premiere_mise_en_circulation', models.DateField()),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_vehicle', to='vehicle.categorymodel')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_vehicle', to='user.personmodel')),
            ],
        ),
    ]
