# Generated by Django 5.1.4 on 2025-01-04 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='person',
        ),
    ]
