# Generated by Django 5.1.4 on 2025-01-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_rename_nom_categorymodel_libelle_categorymodel_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='valeur',
        ),
    ]
