# Generated by Django 5.1.4 on 2025-01-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_souscription', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='en attente', max_length=20)),
                ('numero_attestation', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
    ]
