# Generated by Django 5.1.4 on 2025-01-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_remove_subscriptionmodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionmodel',
            name='produit',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
